// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: entities.sql

package pgdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	pgvector "github.com/pgvector/pgvector-go"
)

const addEntityAlias = `-- name: AddEntityAlias :exec
INSERT INTO entity_aliases (entity_id, alias)
VALUES ($1, $2)
ON CONFLICT (entity_id, alias) DO NOTHING
`

type AddEntityAliasParams struct {
	EntityID int64
	Alias    string
}

// Alternate names that resolve to the same entity (renames, "Bob"↔"Robert").
func (q *Queries) AddEntityAlias(ctx context.Context, arg AddEntityAliasParams) error {
	_, err := q.db.Exec(ctx, addEntityAlias, arg.EntityID, arg.Alias)
	return err
}

const getEntityBySlug = `-- name: GetEntityBySlug :one
SELECT id, profile, vault, slug, name, description, embedding, created_at, updated_at, embedding_model, embedding_version FROM entities
WHERE profile = $1 AND vault = $2 AND slug = $3
`

type GetEntityBySlugParams struct {
	Profile string
	Vault   string
	Slug    string
}

func (q *Queries) GetEntityBySlug(ctx context.Context, arg GetEntityBySlugParams) (Entity, error) {
	row := q.db.QueryRow(ctx, getEntityBySlug, arg.Profile, arg.Vault, arg.Slug)
	var i Entity
	err := row.Scan(
		&i.ID,
		&i.Profile,
		&i.Vault,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Embedding,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmbeddingModel,
		&i.EmbeddingVersion,
	)
	return i, err
}

const linkRecordEntity = `-- name: LinkRecordEntity :exec
INSERT INTO record_entities (record_id, entity_id)
VALUES ($1, $2)
ON CONFLICT (record_id, entity_id) DO NOTHING
`

type LinkRecordEntityParams struct {
	RecordID int64
	EntityID int64
}

// Forward edge: this record mentions this entity.
func (q *Queries) LinkRecordEntity(ctx context.Context, arg LinkRecordEntityParams) error {
	_, err := q.db.Exec(ctx, linkRecordEntity, arg.RecordID, arg.EntityID)
	return err
}

const recordsMentioningEntity = `-- name: RecordsMentioningEntity :many
SELECT r.id, r.profile, r.vault, r.sha, r.kind, r.memory_type, r.title, r.raw_body, r.body, r.source_url, r.source, r.tags, r.captured_at, r.created_at, r.updated_at, r.reliability, r.topic, r.gate_reason, r.synthesised, r.minio_key, r.mime_type, r.size_bytes, r.original_filename, r.extracted_text, r.embedding, r.embedding_model, r.embedding_version FROM records r
JOIN record_entities re ON re.record_id = r.id
JOIN entities e         ON e.id = re.entity_id
WHERE e.profile = $1 AND e.vault = $2 AND e.slug = $3
ORDER BY r.id
`

type RecordsMentioningEntityParams struct {
	Profile string
	Vault   string
	Slug    string
}

// Reverse backlink (the mentioned_by[] replacement): every record that
// mentions the entity identified by slug, within a tenant.
func (q *Queries) RecordsMentioningEntity(ctx context.Context, arg RecordsMentioningEntityParams) ([]Record, error) {
	rows, err := q.db.Query(ctx, recordsMentioningEntity, arg.Profile, arg.Vault, arg.Slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Record{}
	for rows.Next() {
		var i Record
		if err := rows.Scan(
			&i.ID,
			&i.Profile,
			&i.Vault,
			&i.Sha,
			&i.Kind,
			&i.MemoryType,
			&i.Title,
			&i.RawBody,
			&i.Body,
			&i.SourceUrl,
			&i.Source,
			&i.Tags,
			&i.CapturedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Reliability,
			&i.Topic,
			&i.GateReason,
			&i.Synthesised,
			&i.MinioKey,
			&i.MimeType,
			&i.SizeBytes,
			&i.OriginalFilename,
			&i.ExtractedText,
			&i.Embedding,
			&i.EmbeddingModel,
			&i.EmbeddingVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveEntityByAlias = `-- name: ResolveEntityByAlias :one
SELECT e.id, e.profile, e.vault, e.slug, e.name, e.description, e.embedding, e.created_at, e.updated_at, e.embedding_model, e.embedding_version FROM entities e
JOIN entity_aliases a ON a.entity_id = e.id
WHERE e.profile = $1 AND e.vault = $2 AND a.alias = $3
`

type ResolveEntityByAliasParams struct {
	Profile string
	Vault   string
	Alias   string
}

// Find the canonical entity for an alias within a tenant.
func (q *Queries) ResolveEntityByAlias(ctx context.Context, arg ResolveEntityByAliasParams) (Entity, error) {
	row := q.db.QueryRow(ctx, resolveEntityByAlias, arg.Profile, arg.Vault, arg.Alias)
	var i Entity
	err := row.Scan(
		&i.ID,
		&i.Profile,
		&i.Vault,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Embedding,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmbeddingModel,
		&i.EmbeddingVersion,
	)
	return i, err
}

const upsertEntity = `-- name: UpsertEntity :one

INSERT INTO entities (
    profile, vault, slug, name, description,
    embedding, embedding_model, embedding_version
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8
)
ON CONFLICT (profile, vault, slug) DO UPDATE SET
    name        = EXCLUDED.name,
    description = COALESCE(EXCLUDED.description, entities.description)
RETURNING id, profile, vault, slug, name, description, embedding, created_at, updated_at, embedding_model, embedding_version
`

type UpsertEntityParams struct {
	Profile          string
	Vault            string
	Slug             string
	Name             string
	Description      pgtype.Text
	Embedding        *pgvector.Vector
	EmbeddingModel   pgtype.Text
	EmbeddingVersion pgtype.Text
}

// entities.sql — canonical entities, aliases, and the record↔entity join.
// The forward edge (record → entities) is record_entities; the reverse
// ("what mentions X") is just a query over it — no array read-modify-write.
// Canonical-by-slug. A repeat upsert refreshes name and only overwrites the
// description when a non-NULL one is supplied (COALESCE keeps the old blurb).
func (q *Queries) UpsertEntity(ctx context.Context, arg UpsertEntityParams) (Entity, error) {
	row := q.db.QueryRow(ctx, upsertEntity,
		arg.Profile,
		arg.Vault,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.Embedding,
		arg.EmbeddingModel,
		arg.EmbeddingVersion,
	)
	var i Entity
	err := row.Scan(
		&i.ID,
		&i.Profile,
		&i.Vault,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Embedding,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmbeddingModel,
		&i.EmbeddingVersion,
	)
	return i, err
}
