// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: facts.sql

package pgdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getFact = `-- name: GetFact :one

SELECT id, profile, vault, entity_id, attribute, value, source_record_id, confidence, valid_from, updated_at FROM facts
WHERE entity_id = $1 AND attribute = $2
`

type GetFactParams struct {
	EntityID  int64
	Attribute string
}

// facts.sql — mutable state: the referent-keyed projection.
// (entity, attribute) is unique: the CURRENT value is one row you UPSERT;
// the prior value moves to fact_history (versioned, never destructive).
func (q *Queries) GetFact(ctx context.Context, arg GetFactParams) (Fact, error) {
	row := q.db.QueryRow(ctx, getFact, arg.EntityID, arg.Attribute)
	var i Fact
	err := row.Scan(
		&i.ID,
		&i.Profile,
		&i.Vault,
		&i.EntityID,
		&i.Attribute,
		&i.Value,
		&i.SourceRecordID,
		&i.Confidence,
		&i.ValidFrom,
		&i.UpdatedAt,
	)
	return i, err
}

const insertFactHistory = `-- name: InsertFactHistory :exec
INSERT INTO fact_history (
    profile, vault, entity_id, attribute, value,
    source_record_id, valid_from, superseded_by_record_id
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8
)
`

type InsertFactHistoryParams struct {
	Profile              string
	Vault                string
	EntityID             int64
	Attribute            string
	Value                string
	SourceRecordID       pgtype.Int8
	ValidFrom            pgtype.Timestamptz
	SupersededByRecordID pgtype.Int8
}

// Append a superseded fact value into the immutable history.
func (q *Queries) InsertFactHistory(ctx context.Context, arg InsertFactHistoryParams) error {
	_, err := q.db.Exec(ctx, insertFactHistory,
		arg.Profile,
		arg.Vault,
		arg.EntityID,
		arg.Attribute,
		arg.Value,
		arg.SourceRecordID,
		arg.ValidFrom,
		arg.SupersededByRecordID,
	)
	return err
}

const listFactsForEntity = `-- name: ListFactsForEntity :many
SELECT id, profile, vault, entity_id, attribute, value, source_record_id, confidence, valid_from, updated_at FROM facts
WHERE entity_id = $1
ORDER BY attribute
`

func (q *Queries) ListFactsForEntity(ctx context.Context, entityID int64) ([]Fact, error) {
	rows, err := q.db.Query(ctx, listFactsForEntity, entityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Fact{}
	for rows.Next() {
		var i Fact
		if err := rows.Scan(
			&i.ID,
			&i.Profile,
			&i.Vault,
			&i.EntityID,
			&i.Attribute,
			&i.Value,
			&i.SourceRecordID,
			&i.Confidence,
			&i.ValidFrom,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFact = `-- name: UpsertFact :one
INSERT INTO facts (
    profile, vault, entity_id, attribute, value, source_record_id, confidence
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
ON CONFLICT (entity_id, attribute) DO UPDATE SET
    value            = EXCLUDED.value,
    source_record_id = EXCLUDED.source_record_id,
    confidence       = EXCLUDED.confidence
RETURNING id, profile, vault, entity_id, attribute, value, source_record_id, confidence, valid_from, updated_at
`

type UpsertFactParams struct {
	Profile        string
	Vault          string
	EntityID       int64
	Attribute      string
	Value          string
	SourceRecordID pgtype.Int8
	Confidence     pgtype.Float4
}

// Set the current value for (entity, attribute). On conflict, overwrite the
// value, provenance, and confidence (caller archives the old value into
// fact_history first via InsertFactHistory).
func (q *Queries) UpsertFact(ctx context.Context, arg UpsertFactParams) (Fact, error) {
	row := q.db.QueryRow(ctx, upsertFact,
		arg.Profile,
		arg.Vault,
		arg.EntityID,
		arg.Attribute,
		arg.Value,
		arg.SourceRecordID,
		arg.Confidence,
	)
	var i Fact
	err := row.Scan(
		&i.ID,
		&i.Profile,
		&i.Vault,
		&i.EntityID,
		&i.Attribute,
		&i.Value,
		&i.SourceRecordID,
		&i.Confidence,
		&i.ValidFrom,
		&i.UpdatedAt,
	)
	return i, err
}
