// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package pgdb

import (
	"github.com/jackc/pgx/v5/pgtype"
	pgvector "github.com/pgvector/pgvector-go"
)

type Entity struct {
	ID               int64
	Profile          string
	Vault            string
	Slug             string
	Name             string
	Description      pgtype.Text
	Embedding        *pgvector.Vector
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	EmbeddingModel   pgtype.Text
	EmbeddingVersion pgtype.Text
}

type EntityAlias struct {
	ID        int64
	EntityID  int64
	Alias     string
	CreatedAt pgtype.Timestamptz
}

type Fact struct {
	ID             int64
	Profile        string
	Vault          string
	EntityID       int64
	Attribute      string
	Value          string
	SourceRecordID pgtype.Int8
	Confidence     pgtype.Float4
	ValidFrom      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type FactHistory struct {
	ID                   int64
	Profile              string
	Vault                string
	EntityID             int64
	Attribute            string
	Value                string
	SourceRecordID       pgtype.Int8
	ValidFrom            pgtype.Timestamptz
	ValidTo              pgtype.Timestamptz
	SupersededByRecordID pgtype.Int8
}

type Record struct {
	ID               int64
	Profile          string
	Vault            string
	Sha              string
	Kind             string
	MemoryType       pgtype.Text
	Title            string
	RawBody          pgtype.Text
	Body             pgtype.Text
	SourceUrl        pgtype.Text
	Source           []string
	Tags             []string
	CapturedAt       pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	Reliability      pgtype.Text
	Topic            pgtype.Text
	GateReason       pgtype.Text
	Synthesised      bool
	MinioKey         pgtype.Text
	MimeType         pgtype.Text
	SizeBytes        pgtype.Int8
	OriginalFilename pgtype.Text
	ExtractedText    pgtype.Text
	Embedding        *pgvector.Vector
	EmbeddingModel   pgtype.Text
	EmbeddingVersion pgtype.Text
}

type RecordEntity struct {
	RecordID int64
	EntityID int64
}
