// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package pgdb

import (
	"context"
)

type Querier interface {
	// Alternate names that resolve to the same entity (renames, "Bob"↔"Robert").
	AddEntityAlias(ctx context.Context, arg AddEntityAliasParams) error
	CountUnsynthesised(ctx context.Context, arg CountUnsynthesisedParams) (int64, error)
	GetEntityBySlug(ctx context.Context, arg GetEntityBySlugParams) (Entity, error)
	// facts.sql — mutable state: the referent-keyed projection.
	// (entity, attribute) is unique: the CURRENT value is one row you UPSERT;
	// the prior value moves to fact_history (versioned, never destructive).
	GetFact(ctx context.Context, arg GetFactParams) (Fact, error)
	GetRecordByID(ctx context.Context, id int64) (Record, error)
	GetRecordBySHA(ctx context.Context, arg GetRecordBySHAParams) (Record, error)
	// Append a superseded fact value into the immutable history.
	InsertFactHistory(ctx context.Context, arg InsertFactHistoryParams) error
	// Forward edge: this record mentions this entity.
	LinkRecordEntity(ctx context.Context, arg LinkRecordEntityParams) error
	ListFactsForEntity(ctx context.Context, entityID int64) ([]Fact, error)
	// The resynth scan: records still awaiting the gate + distill + embed pass.
	// Rows may carry a NULL embedding, exercising the nullable vector override.
	ListUnsynthesised(ctx context.Context, arg ListUnsynthesisedParams) ([]Record, error)
	// Fill in the derived fields after the synthesis pipeline runs.
	// updated_at is bumped by the records_set_updated_at trigger.
	MarkRecordSynthesised(ctx context.Context, arg MarkRecordSynthesisedParams) error
	// Reverse backlink (the mentioned_by[] replacement): every record that
	// mentions the entity identified by slug, within a tenant.
	RecordsMentioningEntity(ctx context.Context, arg RecordsMentioningEntityParams) ([]Record, error)
	// Find the canonical entity for an alias within a tenant.
	ResolveEntityByAlias(ctx context.Context, arg ResolveEntityByAliasParams) (Entity, error)
	// Attachment enrichment: store OCR / pdftotext / office-extract output.
	SetRecordExtractedText(ctx context.Context, arg SetRecordExtractedTextParams) error
	// entities.sql — canonical entities, aliases, and the record↔entity join.
	// The forward edge (record → entities) is record_entities; the reverse
	// ("what mentions X") is just a query over it — no array read-modify-write.
	// Canonical-by-slug. A repeat upsert refreshes name and only overwrites the
	// description when a non-NULL one is supplied (COALESCE keeps the old blurb).
	UpsertEntity(ctx context.Context, arg UpsertEntityParams) (Entity, error)
	// Set the current value for (entity, attribute). On conflict, overwrite the
	// value, provenance, and confidence (caller archives the old value into
	// fact_history first via InsertFactHistory).
	UpsertFact(ctx context.Context, arg UpsertFactParams) (Fact, error)
	// records.sql — the immutable content-addressed knowledge log.
	// Dedup is by (profile, vault, sha): a conflict means "already have it".
	// Content-addressed insert. ON CONFLICT DO NOTHING returns no row when the
	// (profile, vault, sha) already exists — callers fall back to GetRecordBySHA.
	UpsertRecord(ctx context.Context, arg UpsertRecordParams) (Record, error)
}

var _ Querier = (*Queries)(nil)
