// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package pgdb

import (
	"context"
)

type Querier interface {
	// Alternate names that resolve to the same entity (renames, "Bob"↔"Robert").
	AddEntityAlias(ctx context.Context, arg AddEntityAliasParams) error
	CountUnsynthesised(ctx context.Context, arg CountUnsynthesisedParams) (int64, error)
	// The brain_forget primitive (issue #72): delete one record by its
	// content-addressed identity, RETURNING its id so the caller can enqueue
	// a projection delete in the same tx. Returns pgx.ErrNoRows when the SHA
	// isn't present — the handler reports forgotten=false rather than lying.
	DeleteRecordBySHA(ctx context.Context, arg DeleteRecordBySHAParams) (int64, error)
	GetEntityBySlug(ctx context.Context, arg GetEntityBySlugParams) (Entity, error)
	// facts.sql — mutable state: the referent-keyed projection.
	// (entity, attribute) is unique: the CURRENT value is one row you UPSERT;
	// the prior value moves to fact_history (versioned, never destructive).
	GetFact(ctx context.Context, arg GetFactParams) (Fact, error)
	GetRecordByID(ctx context.Context, id int64) (Record, error)
	GetRecordBySHA(ctx context.Context, arg GetRecordBySHAParams) (Record, error)
	// Append a superseded fact value into the immutable history.
	InsertFactHistory(ctx context.Context, arg InsertFactHistoryParams) error
	// Forward edge: this record mentions this entity.
	LinkRecordEntity(ctx context.Context, arg LinkRecordEntityParams) error
	ListFactsForEntity(ctx context.Context, entityID int64) ([]Fact, error)
	// Mart projection scan (pbrainctl mart): keyset-paginated enumeration of a
	// tenant's records with optional facet filters. This is the generic "list
	// records" read the resynth-only ListUnsynthesised never provided; the core
	// stays ignorant of marts — a mart is just a consumer of this + the HTTP
	// endpoint over it.
	//
	// Array filters use the coalesce(array_length(...),0)=0 guard rather than a
	// bare IS NULL so a nil []string param cleanly means "no filter": pgx encodes
	// a nil slice as an empty array (not SQL NULL), so an IS NULL guard would
	// never fire and an empty filter would wrongly match nothing. tags/source use
	// the array-overlap operator && ("carries ANY of these"), GIN-accelerated by
	// records_tags_gin / records_source_gin; kind/topic/reliability use = ANY.
	// The id > @after_id keyset walks the PK deterministically; @lim bounds it.
	ListRecords(ctx context.Context, arg ListRecordsParams) ([]Record, error)
	// Change feed for incremental mart refresh (pbrainctl mart sync). Same facet
	// filters as ListRecords, but ordered by the records_set_updated_at-maintained
	// updated_at so a caller can ask "what changed since my cursor". The cursor is
	// COMPOUND — (updated_at, id) — because many rows can share an updated_at
	// (a batch synth pass); keyset `updated_at > @since OR (updated_at = @since AND
	// id > @after_id)` neither skips nor duplicates across page boundaries the way
	// a bare `updated_at > @since` would. Deletes are NOT visible here (a forgotten
	// row simply stops appearing) — pruning is a periodic full rebuild's job.
	ListRecordsSince(ctx context.Context, arg ListRecordsSinceParams) ([]Record, error)
	// The resynth scan: records still awaiting the gate + distill + embed pass.
	// Rows may carry a NULL embedding, exercising the nullable vector override.
	ListUnsynthesised(ctx context.Context, arg ListUnsynthesisedParams) ([]Record, error)
	// Fill in the derived fields after the synthesis pipeline runs.
	// updated_at is bumped by the records_set_updated_at trigger.
	MarkRecordSynthesised(ctx context.Context, arg MarkRecordSynthesisedParams) error
	// Reverse backlink (the mentioned_by[] replacement): every record that
	// mentions the entity identified by slug, within a tenant.
	RecordsMentioningEntity(ctx context.Context, arg RecordsMentioningEntityParams) ([]Record, error)
	// Find the canonical entity for an alias within a tenant.
	ResolveEntityByAlias(ctx context.Context, arg ResolveEntityByAliasParams) (Entity, error)
	// Attachment enrichment: store OCR / pdftotext / office-extract output.
	SetRecordExtractedText(ctx context.Context, arg SetRecordExtractedTextParams) error
	// entities.sql — canonical entities, aliases, and the record↔entity join.
	// The forward edge (record → entities) is record_entities; the reverse
	// ("what mentions X") is just a query over it — no array read-modify-write.
	// Canonical-by-slug. A repeat upsert refreshes name and only overwrites the
	// description when a non-NULL one is supplied (COALESCE keeps the old blurb).
	UpsertEntity(ctx context.Context, arg UpsertEntityParams) (Entity, error)
	// Set the current value for (entity, attribute). On conflict, overwrite the
	// value, provenance, and confidence (caller archives the old value into
	// fact_history first via InsertFactHistory).
	UpsertFact(ctx context.Context, arg UpsertFactParams) (Fact, error)
	// records.sql — the immutable content-addressed knowledge log.
	// Dedup is by (profile, vault, sha): a conflict means "already have it".
	// Content-addressed insert carrying the agent-computed embedding so kNN /
	// semantic recall works off the raw write (the synth pass later overwrites
	// it with the canonical embedding via MarkRecordSynthesised). ON CONFLICT
	// DO UPDATE backfills a previously-NULL embedding on re-ingest WITHOUT
	// clobbering an existing one (or any other field) — COALESCE keeps the
	// stored value when present. Unlike DO NOTHING, DO UPDATE RETURNS the row
	// on conflict too, so callers always get the record back.
	UpsertRecord(ctx context.Context, arg UpsertRecordParams) (Record, error)
}

var _ Querier = (*Queries)(nil)
