// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: records.sql

package pgdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	pgvector "github.com/pgvector/pgvector-go"
)

const countUnsynthesised = `-- name: CountUnsynthesised :one
SELECT count(*) FROM records
WHERE profile = $1 AND vault = $2 AND NOT synthesised
`

type CountUnsynthesisedParams struct {
	Profile string
	Vault   string
}

func (q *Queries) CountUnsynthesised(ctx context.Context, arg CountUnsynthesisedParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUnsynthesised, arg.Profile, arg.Vault)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteRecordBySHA = `-- name: DeleteRecordBySHA :one
DELETE FROM records
WHERE profile = $1 AND vault = $2 AND sha = $3
RETURNING id
`

type DeleteRecordBySHAParams struct {
	Profile string
	Vault   string
	Sha     string
}

// The brain_forget primitive (issue #72): delete one record by its
// content-addressed identity, RETURNING its id so the caller can enqueue
// a projection delete in the same tx. Returns pgx.ErrNoRows when the SHA
// isn't present — the handler reports forgotten=false rather than lying.
func (q *Queries) DeleteRecordBySHA(ctx context.Context, arg DeleteRecordBySHAParams) (int64, error) {
	row := q.db.QueryRow(ctx, deleteRecordBySHA, arg.Profile, arg.Vault, arg.Sha)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getRecordByID = `-- name: GetRecordByID :one
SELECT id, profile, vault, sha, kind, memory_type, title, raw_body, body, source_url, source, tags, captured_at, created_at, updated_at, reliability, topic, gate_reason, synthesised, minio_key, mime_type, size_bytes, original_filename, extracted_text, embedding, embedding_model, embedding_version, capture_minio_key, capture_size_bytes FROM records WHERE id = $1
`

func (q *Queries) GetRecordByID(ctx context.Context, id int64) (Record, error) {
	row := q.db.QueryRow(ctx, getRecordByID, id)
	var i Record
	err := row.Scan(
		&i.ID,
		&i.Profile,
		&i.Vault,
		&i.Sha,
		&i.Kind,
		&i.MemoryType,
		&i.Title,
		&i.RawBody,
		&i.Body,
		&i.SourceUrl,
		&i.Source,
		&i.Tags,
		&i.CapturedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Reliability,
		&i.Topic,
		&i.GateReason,
		&i.Synthesised,
		&i.MinioKey,
		&i.MimeType,
		&i.SizeBytes,
		&i.OriginalFilename,
		&i.ExtractedText,
		&i.Embedding,
		&i.EmbeddingModel,
		&i.EmbeddingVersion,
		&i.CaptureMinioKey,
		&i.CaptureSizeBytes,
	)
	return i, err
}

const getRecordBySHA = `-- name: GetRecordBySHA :one
SELECT id, profile, vault, sha, kind, memory_type, title, raw_body, body, source_url, source, tags, captured_at, created_at, updated_at, reliability, topic, gate_reason, synthesised, minio_key, mime_type, size_bytes, original_filename, extracted_text, embedding, embedding_model, embedding_version, capture_minio_key, capture_size_bytes FROM records
WHERE profile = $1 AND vault = $2 AND sha = $3
`

type GetRecordBySHAParams struct {
	Profile string
	Vault   string
	Sha     string
}

func (q *Queries) GetRecordBySHA(ctx context.Context, arg GetRecordBySHAParams) (Record, error) {
	row := q.db.QueryRow(ctx, getRecordBySHA, arg.Profile, arg.Vault, arg.Sha)
	var i Record
	err := row.Scan(
		&i.ID,
		&i.Profile,
		&i.Vault,
		&i.Sha,
		&i.Kind,
		&i.MemoryType,
		&i.Title,
		&i.RawBody,
		&i.Body,
		&i.SourceUrl,
		&i.Source,
		&i.Tags,
		&i.CapturedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Reliability,
		&i.Topic,
		&i.GateReason,
		&i.Synthesised,
		&i.MinioKey,
		&i.MimeType,
		&i.SizeBytes,
		&i.OriginalFilename,
		&i.ExtractedText,
		&i.Embedding,
		&i.EmbeddingModel,
		&i.EmbeddingVersion,
		&i.CaptureMinioKey,
		&i.CaptureSizeBytes,
	)
	return i, err
}

const listRecords = `-- name: ListRecords :many
SELECT id, profile, vault, sha, kind, memory_type, title, raw_body, body, source_url, source, tags, captured_at, created_at, updated_at, reliability, topic, gate_reason, synthesised, minio_key, mime_type, size_bytes, original_filename, extracted_text, embedding, embedding_model, embedding_version, capture_minio_key, capture_size_bytes FROM records
WHERE profile = $1
  AND vault   = $2
  AND synthesised = $3
  AND (coalesce(array_length($4::text[], 1), 0) = 0         OR kind = ANY($4::text[]))
  AND (coalesce(array_length($5::text[], 1), 0) = 0        OR topic = ANY($5::text[]))
  AND (coalesce(array_length($6::text[], 1), 0) = 0 OR reliability = ANY($6::text[]))
  AND (coalesce(array_length($7::text[], 1), 0) = 0      OR tags && $7::text[])
  AND (coalesce(array_length($8::text[], 1), 0) = 0    OR source && $8::text[])
  AND id > $9
ORDER BY id
LIMIT $10
`

type ListRecordsParams struct {
	Profile       string
	Vault         string
	Synthesised   bool
	Kinds         []string
	Topics        []string
	Reliabilities []string
	TagsAny       []string
	SourceAny     []string
	AfterID       int64
	Lim           int32
}

// Mart projection scan (pbrainctl mart): keyset-paginated enumeration of a
// tenant's records with optional facet filters. This is the generic "list
// records" read the resynth-only ListUnsynthesised never provided; the core
// stays ignorant of marts — a mart is just a consumer of this + the HTTP
// endpoint over it.
//
// Array filters use the coalesce(array_length(...),0)=0 guard rather than a
// bare IS NULL so a nil []string param cleanly means "no filter": pgx encodes
// a nil slice as an empty array (not SQL NULL), so an IS NULL guard would
// never fire and an empty filter would wrongly match nothing. tags/source use
// the array-overlap operator && ("carries ANY of these"), GIN-accelerated by
// records_tags_gin / records_source_gin; kind/topic/reliability use = ANY.
// The id > @after_id keyset walks the PK deterministically; @lim bounds it.
func (q *Queries) ListRecords(ctx context.Context, arg ListRecordsParams) ([]Record, error) {
	rows, err := q.db.Query(ctx, listRecords,
		arg.Profile,
		arg.Vault,
		arg.Synthesised,
		arg.Kinds,
		arg.Topics,
		arg.Reliabilities,
		arg.TagsAny,
		arg.SourceAny,
		arg.AfterID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Record{}
	for rows.Next() {
		var i Record
		if err := rows.Scan(
			&i.ID,
			&i.Profile,
			&i.Vault,
			&i.Sha,
			&i.Kind,
			&i.MemoryType,
			&i.Title,
			&i.RawBody,
			&i.Body,
			&i.SourceUrl,
			&i.Source,
			&i.Tags,
			&i.CapturedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Reliability,
			&i.Topic,
			&i.GateReason,
			&i.Synthesised,
			&i.MinioKey,
			&i.MimeType,
			&i.SizeBytes,
			&i.OriginalFilename,
			&i.ExtractedText,
			&i.Embedding,
			&i.EmbeddingModel,
			&i.EmbeddingVersion,
			&i.CaptureMinioKey,
			&i.CaptureSizeBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnsynthesised = `-- name: ListUnsynthesised :many
SELECT id, profile, vault, sha, kind, memory_type, title, raw_body, body, source_url, source, tags, captured_at, created_at, updated_at, reliability, topic, gate_reason, synthesised, minio_key, mime_type, size_bytes, original_filename, extracted_text, embedding, embedding_model, embedding_version, capture_minio_key, capture_size_bytes FROM records
WHERE profile = $1 AND vault = $2 AND NOT synthesised
ORDER BY id
LIMIT $3
`

type ListUnsynthesisedParams struct {
	Profile string
	Vault   string
	Lim     int32
}

// The resynth scan: records still awaiting the gate + distill + embed pass.
// Rows may carry a NULL embedding, exercising the nullable vector override.
func (q *Queries) ListUnsynthesised(ctx context.Context, arg ListUnsynthesisedParams) ([]Record, error) {
	rows, err := q.db.Query(ctx, listUnsynthesised, arg.Profile, arg.Vault, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Record{}
	for rows.Next() {
		var i Record
		if err := rows.Scan(
			&i.ID,
			&i.Profile,
			&i.Vault,
			&i.Sha,
			&i.Kind,
			&i.MemoryType,
			&i.Title,
			&i.RawBody,
			&i.Body,
			&i.SourceUrl,
			&i.Source,
			&i.Tags,
			&i.CapturedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Reliability,
			&i.Topic,
			&i.GateReason,
			&i.Synthesised,
			&i.MinioKey,
			&i.MimeType,
			&i.SizeBytes,
			&i.OriginalFilename,
			&i.ExtractedText,
			&i.Embedding,
			&i.EmbeddingModel,
			&i.EmbeddingVersion,
			&i.CaptureMinioKey,
			&i.CaptureSizeBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRecordSynthesised = `-- name: MarkRecordSynthesised :exec
UPDATE records SET
    body               = $1,
    reliability        = $2,
    topic              = $3,
    gate_reason        = $4,
    synthesised        = true,
    embedding          = $5,
    embedding_model    = $6,
    embedding_version  = $7,
    capture_minio_key  = $8,
    capture_size_bytes = $9
WHERE id = $10
`

type MarkRecordSynthesisedParams struct {
	Body             pgtype.Text
	Reliability      pgtype.Text
	Topic            pgtype.Text
	GateReason       pgtype.Text
	Embedding        *pgvector.Vector
	EmbeddingModel   pgtype.Text
	EmbeddingVersion pgtype.Text
	CaptureMinioKey  pgtype.Text
	CaptureSizeBytes pgtype.Int8
	ID               int64
}

// Fill in the derived fields after the synthesis pipeline runs.
// updated_at is bumped by the records_set_updated_at trigger.
func (q *Queries) MarkRecordSynthesised(ctx context.Context, arg MarkRecordSynthesisedParams) error {
	_, err := q.db.Exec(ctx, markRecordSynthesised,
		arg.Body,
		arg.Reliability,
		arg.Topic,
		arg.GateReason,
		arg.Embedding,
		arg.EmbeddingModel,
		arg.EmbeddingVersion,
		arg.CaptureMinioKey,
		arg.CaptureSizeBytes,
		arg.ID,
	)
	return err
}

const setRecordExtractedText = `-- name: SetRecordExtractedText :exec
UPDATE records SET extracted_text = $1 WHERE id = $2
`

type SetRecordExtractedTextParams struct {
	ExtractedText pgtype.Text
	ID            int64
}

// Attachment enrichment: store OCR / pdftotext / office-extract output.
func (q *Queries) SetRecordExtractedText(ctx context.Context, arg SetRecordExtractedTextParams) error {
	_, err := q.db.Exec(ctx, setRecordExtractedText, arg.ExtractedText, arg.ID)
	return err
}

const upsertRecord = `-- name: UpsertRecord :one

INSERT INTO records (
    profile, vault, sha, kind, memory_type,
    title, raw_body, source_url, source, tags, captured_at,
    minio_key, mime_type, size_bytes, original_filename, embedding
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10, $11,
    $12, $13, $14, $15, $16
)
ON CONFLICT (profile, vault, sha) DO UPDATE SET
    embedding = COALESCE(records.embedding, EXCLUDED.embedding)
RETURNING id, profile, vault, sha, kind, memory_type, title, raw_body, body, source_url, source, tags, captured_at, created_at, updated_at, reliability, topic, gate_reason, synthesised, minio_key, mime_type, size_bytes, original_filename, extracted_text, embedding, embedding_model, embedding_version, capture_minio_key, capture_size_bytes
`

type UpsertRecordParams struct {
	Profile          string
	Vault            string
	Sha              string
	Kind             string
	MemoryType       pgtype.Text
	Title            string
	RawBody          pgtype.Text
	SourceUrl        pgtype.Text
	Source           []string
	Tags             []string
	CapturedAt       pgtype.Timestamptz
	MinioKey         pgtype.Text
	MimeType         pgtype.Text
	SizeBytes        pgtype.Int8
	OriginalFilename pgtype.Text
	Embedding        *pgvector.Vector
}

// records.sql — the immutable content-addressed knowledge log.
// Dedup is by (profile, vault, sha): a conflict means "already have it".
// Content-addressed insert carrying the agent-computed embedding so kNN /
// semantic recall works off the raw write (the synth pass later overwrites
// it with the canonical embedding via MarkRecordSynthesised). ON CONFLICT
// DO UPDATE backfills a previously-NULL embedding on re-ingest WITHOUT
// clobbering an existing one (or any other field) — COALESCE keeps the
// stored value when present. Unlike DO NOTHING, DO UPDATE RETURNS the row
// on conflict too, so callers always get the record back.
func (q *Queries) UpsertRecord(ctx context.Context, arg UpsertRecordParams) (Record, error) {
	row := q.db.QueryRow(ctx, upsertRecord,
		arg.Profile,
		arg.Vault,
		arg.Sha,
		arg.Kind,
		arg.MemoryType,
		arg.Title,
		arg.RawBody,
		arg.SourceUrl,
		arg.Source,
		arg.Tags,
		arg.CapturedAt,
		arg.MinioKey,
		arg.MimeType,
		arg.SizeBytes,
		arg.OriginalFilename,
		arg.Embedding,
	)
	var i Record
	err := row.Scan(
		&i.ID,
		&i.Profile,
		&i.Vault,
		&i.Sha,
		&i.Kind,
		&i.MemoryType,
		&i.Title,
		&i.RawBody,
		&i.Body,
		&i.SourceUrl,
		&i.Source,
		&i.Tags,
		&i.CapturedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Reliability,
		&i.Topic,
		&i.GateReason,
		&i.Synthesised,
		&i.MinioKey,
		&i.MimeType,
		&i.SizeBytes,
		&i.OriginalFilename,
		&i.ExtractedText,
		&i.Embedding,
		&i.EmbeddingModel,
		&i.EmbeddingVersion,
		&i.CaptureMinioKey,
		&i.CaptureSizeBytes,
	)
	return i, err
}
