// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: records.sql

package pgdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	pgvector "github.com/pgvector/pgvector-go"
)

const countUnsynthesised = `-- name: CountUnsynthesised :one
SELECT count(*) FROM records
WHERE profile = $1 AND vault = $2 AND NOT synthesised
`

type CountUnsynthesisedParams struct {
	Profile string
	Vault   string
}

func (q *Queries) CountUnsynthesised(ctx context.Context, arg CountUnsynthesisedParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUnsynthesised, arg.Profile, arg.Vault)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getRecordByID = `-- name: GetRecordByID :one
SELECT id, profile, vault, sha, kind, memory_type, title, raw_body, body, source_url, source, tags, captured_at, created_at, updated_at, reliability, topic, gate_reason, synthesised, minio_key, mime_type, size_bytes, original_filename, extracted_text, embedding, embedding_model, embedding_version FROM records WHERE id = $1
`

func (q *Queries) GetRecordByID(ctx context.Context, id int64) (Record, error) {
	row := q.db.QueryRow(ctx, getRecordByID, id)
	var i Record
	err := row.Scan(
		&i.ID,
		&i.Profile,
		&i.Vault,
		&i.Sha,
		&i.Kind,
		&i.MemoryType,
		&i.Title,
		&i.RawBody,
		&i.Body,
		&i.SourceUrl,
		&i.Source,
		&i.Tags,
		&i.CapturedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Reliability,
		&i.Topic,
		&i.GateReason,
		&i.Synthesised,
		&i.MinioKey,
		&i.MimeType,
		&i.SizeBytes,
		&i.OriginalFilename,
		&i.ExtractedText,
		&i.Embedding,
		&i.EmbeddingModel,
		&i.EmbeddingVersion,
	)
	return i, err
}

const getRecordBySHA = `-- name: GetRecordBySHA :one
SELECT id, profile, vault, sha, kind, memory_type, title, raw_body, body, source_url, source, tags, captured_at, created_at, updated_at, reliability, topic, gate_reason, synthesised, minio_key, mime_type, size_bytes, original_filename, extracted_text, embedding, embedding_model, embedding_version FROM records
WHERE profile = $1 AND vault = $2 AND sha = $3
`

type GetRecordBySHAParams struct {
	Profile string
	Vault   string
	Sha     string
}

func (q *Queries) GetRecordBySHA(ctx context.Context, arg GetRecordBySHAParams) (Record, error) {
	row := q.db.QueryRow(ctx, getRecordBySHA, arg.Profile, arg.Vault, arg.Sha)
	var i Record
	err := row.Scan(
		&i.ID,
		&i.Profile,
		&i.Vault,
		&i.Sha,
		&i.Kind,
		&i.MemoryType,
		&i.Title,
		&i.RawBody,
		&i.Body,
		&i.SourceUrl,
		&i.Source,
		&i.Tags,
		&i.CapturedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Reliability,
		&i.Topic,
		&i.GateReason,
		&i.Synthesised,
		&i.MinioKey,
		&i.MimeType,
		&i.SizeBytes,
		&i.OriginalFilename,
		&i.ExtractedText,
		&i.Embedding,
		&i.EmbeddingModel,
		&i.EmbeddingVersion,
	)
	return i, err
}

const listUnsynthesised = `-- name: ListUnsynthesised :many
SELECT id, profile, vault, sha, kind, memory_type, title, raw_body, body, source_url, source, tags, captured_at, created_at, updated_at, reliability, topic, gate_reason, synthesised, minio_key, mime_type, size_bytes, original_filename, extracted_text, embedding, embedding_model, embedding_version FROM records
WHERE profile = $1 AND vault = $2 AND NOT synthesised
ORDER BY id
LIMIT $3
`

type ListUnsynthesisedParams struct {
	Profile string
	Vault   string
	Lim     int32
}

// The resynth scan: records still awaiting the gate + distill + embed pass.
// Rows may carry a NULL embedding, exercising the nullable vector override.
func (q *Queries) ListUnsynthesised(ctx context.Context, arg ListUnsynthesisedParams) ([]Record, error) {
	rows, err := q.db.Query(ctx, listUnsynthesised, arg.Profile, arg.Vault, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Record{}
	for rows.Next() {
		var i Record
		if err := rows.Scan(
			&i.ID,
			&i.Profile,
			&i.Vault,
			&i.Sha,
			&i.Kind,
			&i.MemoryType,
			&i.Title,
			&i.RawBody,
			&i.Body,
			&i.SourceUrl,
			&i.Source,
			&i.Tags,
			&i.CapturedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Reliability,
			&i.Topic,
			&i.GateReason,
			&i.Synthesised,
			&i.MinioKey,
			&i.MimeType,
			&i.SizeBytes,
			&i.OriginalFilename,
			&i.ExtractedText,
			&i.Embedding,
			&i.EmbeddingModel,
			&i.EmbeddingVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRecordSynthesised = `-- name: MarkRecordSynthesised :exec
UPDATE records SET
    body              = $1,
    reliability       = $2,
    topic             = $3,
    gate_reason       = $4,
    synthesised       = true,
    embedding         = $5,
    embedding_model   = $6,
    embedding_version = $7
WHERE id = $8
`

type MarkRecordSynthesisedParams struct {
	Body             pgtype.Text
	Reliability      pgtype.Text
	Topic            pgtype.Text
	GateReason       pgtype.Text
	Embedding        *pgvector.Vector
	EmbeddingModel   pgtype.Text
	EmbeddingVersion pgtype.Text
	ID               int64
}

// Fill in the derived fields after the synthesis pipeline runs.
// updated_at is bumped by the records_set_updated_at trigger.
func (q *Queries) MarkRecordSynthesised(ctx context.Context, arg MarkRecordSynthesisedParams) error {
	_, err := q.db.Exec(ctx, markRecordSynthesised,
		arg.Body,
		arg.Reliability,
		arg.Topic,
		arg.GateReason,
		arg.Embedding,
		arg.EmbeddingModel,
		arg.EmbeddingVersion,
		arg.ID,
	)
	return err
}

const setRecordExtractedText = `-- name: SetRecordExtractedText :exec
UPDATE records SET extracted_text = $1 WHERE id = $2
`

type SetRecordExtractedTextParams struct {
	ExtractedText pgtype.Text
	ID            int64
}

// Attachment enrichment: store OCR / pdftotext / office-extract output.
func (q *Queries) SetRecordExtractedText(ctx context.Context, arg SetRecordExtractedTextParams) error {
	_, err := q.db.Exec(ctx, setRecordExtractedText, arg.ExtractedText, arg.ID)
	return err
}

const upsertRecord = `-- name: UpsertRecord :one

INSERT INTO records (
    profile, vault, sha, kind, memory_type,
    title, raw_body, source_url, source, tags, captured_at,
    minio_key, mime_type, size_bytes, original_filename
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10, $11,
    $12, $13, $14, $15
)
ON CONFLICT (profile, vault, sha) DO NOTHING
RETURNING id, profile, vault, sha, kind, memory_type, title, raw_body, body, source_url, source, tags, captured_at, created_at, updated_at, reliability, topic, gate_reason, synthesised, minio_key, mime_type, size_bytes, original_filename, extracted_text, embedding, embedding_model, embedding_version
`

type UpsertRecordParams struct {
	Profile          string
	Vault            string
	Sha              string
	Kind             string
	MemoryType       pgtype.Text
	Title            string
	RawBody          pgtype.Text
	SourceUrl        pgtype.Text
	Source           []string
	Tags             []string
	CapturedAt       pgtype.Timestamptz
	MinioKey         pgtype.Text
	MimeType         pgtype.Text
	SizeBytes        pgtype.Int8
	OriginalFilename pgtype.Text
}

// records.sql — the immutable content-addressed knowledge log.
// Dedup is by (profile, vault, sha): a conflict means "already have it".
// Content-addressed insert. ON CONFLICT DO NOTHING returns no row when the
// (profile, vault, sha) already exists — callers fall back to GetRecordBySHA.
func (q *Queries) UpsertRecord(ctx context.Context, arg UpsertRecordParams) (Record, error) {
	row := q.db.QueryRow(ctx, upsertRecord,
		arg.Profile,
		arg.Vault,
		arg.Sha,
		arg.Kind,
		arg.MemoryType,
		arg.Title,
		arg.RawBody,
		arg.SourceUrl,
		arg.Source,
		arg.Tags,
		arg.CapturedAt,
		arg.MinioKey,
		arg.MimeType,
		arg.SizeBytes,
		arg.OriginalFilename,
	)
	var i Record
	err := row.Scan(
		&i.ID,
		&i.Profile,
		&i.Vault,
		&i.Sha,
		&i.Kind,
		&i.MemoryType,
		&i.Title,
		&i.RawBody,
		&i.Body,
		&i.SourceUrl,
		&i.Source,
		&i.Tags,
		&i.CapturedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Reliability,
		&i.Topic,
		&i.GateReason,
		&i.Synthesised,
		&i.MinioKey,
		&i.MimeType,
		&i.SizeBytes,
		&i.OriginalFilename,
		&i.ExtractedText,
		&i.Embedding,
		&i.EmbeddingModel,
		&i.EmbeddingVersion,
	)
	return i, err
}
