package mart

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/neverprepared/phantom-brain/internal/brain"
)

// MarkerFile is written at the root of every mart directory. Its presence is
// how Build proves it owns a directory before wiping or overwriting it — the
// guard that stops a mart from clobbering hand-authored notes.
const MarkerFile = ".pbrain-mart"

const indexFile = "index.md"

// RecordSource yields one keyset page of records at a time. Build is written
// against this interface so the future mart-daemon (an updated_at change-feed
// source) reuses Build and the renderer verbatim — only the source differs.
type RecordSource interface {
	Page(ctx context.Context, afterID int64) (recs []brain.RecordDTO, next int64, err error)
}

// ClientSource is the MVP RecordSource: it pages the daemon's
// GET /api/brain/records over the public HTTP client.
type ClientSource struct {
	Client   *brain.Client
	Filters  Filters
	PageSize int
}

// Page implements RecordSource.
func (s ClientSource) Page(ctx context.Context, afterID int64) ([]brain.RecordDTO, int64, error) {
	limit := s.PageSize
	if limit <= 0 {
		limit = 100
	}
	resp, err := s.Client.ListRecords(ctx, brain.ListRecordsRequest{
		AfterID:     afterID,
		Limit:       limit,
		Kinds:       s.Filters.Kinds,
		Tags:        s.Filters.Tags,
		Sources:     s.Filters.Sources,
		Topic:       s.Filters.Topic,
		Reliability: s.Filters.Reliability,
		Synthesised: s.Filters.Synthesised,
	})
	if err != nil {
		return nil, 0, err
	}
	return resp.Records, resp.NextAfterID, nil
}

// Result summarises a build.
type Result struct {
	RecordsWritten int
	DestPath       string
}

// Build renders the mart described by spec into spec.Dest, paging through src.
//
// Ownership safety (critical): Build refuses to wipe or write into a non-empty
// directory that lacks the MarkerFile — a mart only ever touches directories
// it created. An ephemeral mart clean-rebuilds (wipe → recreate → marker); a
// non-ephemeral mart overwrites in place by the record's deterministic
// filename. index.md is written last as the Obsidian entry point.
func Build(ctx context.Context, spec Spec, src RecordSource) (Result, error) {
	if err := spec.Validate(); err != nil {
		return Result{}, err
	}

	if err := prepareDest(spec); err != nil {
		return Result{}, err
	}

	type indexRow struct {
		base, title, kind, topic string
	}
	var rows []indexRow
	written := 0

	afterID := int64(0)
	for {
		recs, next, err := src.Page(ctx, afterID)
		if err != nil {
			return Result{}, fmt.Errorf("list records: %w", err)
		}
		for _, rec := range recs {
			data, err := Render(rec)
			if err != nil {
				return Result{}, fmt.Errorf("render %s: %w", rec.SHA, err)
			}
			name := Filename(rec)
			if err := os.WriteFile(filepath.Join(spec.Dest, name), data, 0o644); err != nil {
				return Result{}, fmt.Errorf("write %s: %w", name, err)
			}
			rows = append(rows, indexRow{
				base:  strings.TrimSuffix(name, ".md"),
				title: rec.Title,
				kind:  rec.Kind,
				topic: rec.Topic,
			})
			written++
		}
		if next == 0 || next <= afterID || len(recs) == 0 {
			break
		}
		afterID = next
	}

	// index.md — a table of wikilinks so Obsidian has an entry point.
	var idx strings.Builder
	fmt.Fprintf(&idx, "# %s\n\n", spec.Name)
	fmt.Fprintf(&idx, "Projected from phantom-brain (%s/%s). %d record(s). Generated by `pbrainctl mart build`; do not edit — this directory is rebuilt.\n\n",
		spec.Profile, spec.Vault, written)
	idx.WriteString("| Note | Kind | Topic |\n|------|------|-------|\n")
	for _, r := range rows {
		title := r.title
		if strings.TrimSpace(title) == "" {
			title = "(untitled)"
		}
		fmt.Fprintf(&idx, "| [[%s\\|%s]] | %s | %s |\n", r.base, title, r.kind, r.topic)
	}
	if err := os.WriteFile(filepath.Join(spec.Dest, indexFile), []byte(idx.String()), 0o644); err != nil {
		return Result{}, fmt.Errorf("write index.md: %w", err)
	}

	return Result{RecordsWritten: written, DestPath: spec.Dest}, nil
}

// prepareDest enforces the ownership guard and readies spec.Dest for writing.
func prepareDest(spec Spec) error {
	markerPath := filepath.Join(spec.Dest, MarkerFile)

	info, err := os.Stat(spec.Dest)
	switch {
	case os.IsNotExist(err):
		// Fresh directory — create + claim.
		if err := os.MkdirAll(spec.Dest, 0o755); err != nil {
			return fmt.Errorf("create mart dir: %w", err)
		}
		return writeMarker(spec)
	case err != nil:
		return fmt.Errorf("stat mart dest: %w", err)
	case !info.IsDir():
		return fmt.Errorf("mart dest %q exists and is not a directory", spec.Dest)
	}

	// Directory exists — do we own it?
	owned := fileExists(markerPath)
	if !owned {
		empty, derr := dirEmpty(spec.Dest)
		if derr != nil {
			return derr
		}
		if !empty {
			return fmt.Errorf("refusing to use non-mart directory %q: it is non-empty and lacks the %s marker (point --dest at a dedicated subdirectory the mart can own)",
				spec.Dest, MarkerFile)
		}
		// Empty dir — safe to adopt.
		return writeMarker(spec)
	}

	if spec.Ephemeral {
		// Clean-rebuild: wipe and recreate. Safe — we own it (marker present).
		if err := os.RemoveAll(spec.Dest); err != nil {
			return fmt.Errorf("clean mart dir: %w", err)
		}
		if err := os.MkdirAll(spec.Dest, 0o755); err != nil {
			return fmt.Errorf("recreate mart dir: %w", err)
		}
		return writeMarker(spec)
	}
	// Non-ephemeral: keep existing files, overwrite by deterministic name.
	return writeMarker(spec)
}

func writeMarker(spec Spec) error {
	content := fmt.Sprintf("phantom-brain mart: %s\nprofile: %s\nvault: %s\n", spec.Name, spec.Profile, spec.Vault)
	if err := os.WriteFile(filepath.Join(spec.Dest, MarkerFile), []byte(content), 0o644); err != nil {
		return fmt.Errorf("write mart marker: %w", err)
	}
	return nil
}

func fileExists(p string) bool {
	_, err := os.Stat(p)
	return err == nil
}

func dirEmpty(dir string) (bool, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return false, fmt.Errorf("read mart dest: %w", err)
	}
	return len(entries) == 0, nil
}
